--TEST--
MongoDB\Driver\Manager - appname
--FILE--
<?php
$name1 = str_repeat( "HIPPO", 20 );
$name2 = str_repeat( "HIPPO", 200 );
try
{
	$manager = new \MongoDB\Driver\Manager("mongodb://localhost:27017/?appname={$name1}", [ 'appname' => "2-{$name2}" ] );
}
catch ( \MongoDB\Driver\Exception\InvalidArgumentException $e )
{
	echo $e->getMessage(), "\n";
}
?>
--EXPECT--
Invalid appname value: '2-HIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPOHIPPO'
